Heavy cleanup of the draw_square tutorial.
ros/ros_tutorials pull request #152
Opened 2023-05-22 21:57 UTC by clalancette

In particular:
1. Make it conform to the current ROS 2 style.
2. Add in copyright information.
3. Refactor the entire code into a class, which tidies it up quite a bit and removes a bunch of globals.
4. Make sure to wait for the reset to complete before trying to move the turtle.

2023-05-23 08:14 UTC, ahcorde requested changes
Does it make sense to include `ament_lint_auto` ?

2023-05-23 08:14 UTC, ahcorde commented on turtlesim/tutorials/draw_square.cpp
> +    return fabsf(current_pose_.x - goal_pose_.x) < 0.1 && fabsf(current_pose_.y - goal_pose_.y) < 0.1 && fabsf(current_pose_.theta - goal_pose_.theta) < 0.01;
line < 100

2023-05-23 08:14 UTC, ahcorde commented on turtlesim/tutorials/draw_square.cpp
> +    pose_sub_ = this->create_subscription<turtlesim::msg::Pose>("turtle1/pose", 1, std::bind(&DrawSquare::poseCallback, this, std::placeholders::_1));
line < 100

2023-05-23 13:17 UTC, clalancette commented
> Does it make sense to include ament_lint_auto ?

It's a good question.  I ended up not doing this because I would then have to change the style of all of the files in this package, and I wanted to concentrate on fixing `draw_square` for now.  I think we should eventually clean this up and do that, but as a separate PR.

That said, I'll do the updates you suggest above.

2023-05-23 13:41 UTC, clalancette commented on turtlesim/tutorials/draw_square.cpp
> +    return fabsf(current_pose_.x - goal_pose_.x) < 0.1 && fabsf(current_pose_.y - goal_pose_.y) < 0.1 && fabsf(current_pose_.theta - goal_pose_.theta) < 0.01;
Fixed in 2e574e3

2023-05-23 13:41 UTC, clalancette commented on turtlesim/tutorials/draw_square.cpp
> +    pose_sub_ = this->create_subscription<turtlesim::msg::Pose>("turtle1/pose", 1, std::bind(&DrawSquare::poseCallback, this, std::placeholders::_1));
Fixed in 2e574e3

2023-05-23 13:54 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=18781)](http://ci.ros2.org/job/ci_linux/18781/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=13306)](http://ci.ros2.org/job/ci_linux-aarch64/13306/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19523)](http://ci.ros2.org/job/ci_windows/19523/)

2023-05-23 16:12 UTC, ahcorde approved these changes

2023-05-23 16:12 UTC, merged

2024-09-13 05:23 UTC, gavanderhoorn commented
@clalancette: could this potentially be backported to `humble`?

Without these changes, it looks like `draw_square` is broken on Humble.