Use same QoS for all topic pub/subs
ros/ros_tutorials pull request #161
Opened 2024-01-15 05:29 UTC by Yadunund

This PR ensures that all topic publishers and subscriptions are configured with the same QoS settings. Given that the history depth for the `turtle1/pose` subscription was previously 1, I would observe the `draw_square` executable would sometimes wait indefinitely if the message was dropped. This could happen if the Default reliability is BEST_EFFORT instead of RELIABLE. With the changes, the reliability is RELIABLE and all pub/subs have compatible settings.

2024-01-15 09:13 UTC, ahcorde requested changes

2024-01-15 09:13 UTC, ahcorde commented on turtlesim/include/turtlesim/qos.hpp
> +// Copyright (c) 2009, Willow Garage, Inc.
```suggestion
// Copyright (c) 2024, Open Source Robotics Foundation, Inc.
```

2024-01-15 09:13 UTC, ahcorde commented on turtlesim/include/turtlesim/qos.hpp
> +#include "rclcpp/rclcpp.hpp"
```suggestion
#include <rclcpp/rclcpp.hpp>
```

2024-01-15 09:13 UTC, ahcorde commented on turtlesim/include/turtlesim/qos.hpp
> +}  // namespace turtlesim
```suggestion
}
}  // namespace turtlesim
```

2024-01-15 09:13 UTC, ahcorde commented on turtlesim/src/turtle.cpp
> +
```suggestion
```

2024-01-15 12:00 UTC, Yadunund commented on turtlesim/include/turtlesim/qos.hpp
> +  return rclcpp::QoS(rclcpp::KeepLast(1)).reliable();
Should I set depth as 7 to match what it was in turtle.cpp?
```suggestion
  return rclcpp::QoS(rclcpp::KeepLast(7)).reliable();
```

2024-01-15 12:41 UTC, ahcorde approved these changes

2024-01-15 12:42 UTC, merged

2024-01-16 00:57 UTC, clalancette commented
Did CI get run on this PR?

2024-01-16 08:58 UTC, ahcorde commented
my bad, here we go:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20079)](http://ci.ros2.org/job/ci_linux/20079/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14528)](http://ci.ros2.org/job/ci_linux-aarch64/14528/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20800)](http://ci.ros2.org/job/ci_windows/20800/)

2024-01-16 10:07 UTC, Yadunund commented
I think CI is failing because the branch was deleted. I've triggered a rebuild after restoring the branch.

2024-01-16 15:13 UTC, ahcorde commented
Thank you @Yadunund, all good @clalancette