Create turtlesim_msgs
ros/ros_tutorials pull request #169
Opened 2024-06-27 13:21 UTC by ahcorde

It's more clear when messages and code are in different packages

2024-06-27 13:28 UTC, clalancette requested changes
Ah, this is a good idea.

I've left one nit inline.

Besides that, we'll have to update all of the code in https://github.com/ros/geometry_tutorials/tree/ros2 to deal with this change.  Which also means we'll have to make branches in that repository, since we won't be able to backport this to Jazzy, Iron, and Humble.

We'll also have to update the documentation in https://github.com/ros2/ros2_documentation/, only on the `rolling` branch.

2024-06-27 13:28 UTC, clalancette commented on turtlesim_msgs/CMakeLists.txt
> +ament_package()
Nit: newline at the end of the file.

2024-07-09 11:19 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21414)](http://ci.ros2.org/job/ci_linux/21414/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15709)](http://ci.ros2.org/job/ci_linux-aarch64/15709/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=916)](http://ci.ros2.org/job/ci_linux-rhel/916/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22140)](http://ci.ros2.org/job/ci_windows/22140/)

2024-07-09 12:58 UTC, ahcorde commented
PR updating the documentation https://github.com/ros2/ros2_documentation/pull/4562

2024-07-09 13:03 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21419)](http://ci.ros2.org/job/ci_linux/21419/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15713)](http://ci.ros2.org/job/ci_linux-aarch64/15713/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=920)](http://ci.ros2.org/job/ci_linux-rhel/920/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22144)](http://ci.ros2.org/job/ci_windows/22144/)

2024-07-09 21:08 UTC, clalancette approved these changes
Looks good, this should be merged in tandem with https://github.com/ros/geometry_tutorials/pull/78 and https://github.com/ros2/ros2_documentation/pull/4562

2024-07-10 07:53 UTC, merged